### ISSUE TITLE
Lifetime energy sensor fluctuates 

### ISSUE THREAD

**Issue by B1rdEater** [ProudElm/solaredgeoptimizers#12]
First of all; thanks a lot for you beautiful integration! 

Some panels report a drop in life-time energy production, and will continue on the normal level a few hours later. I use the life-time energy sensor to calculate to daily energy production per panel (and this really messes it up). Which panels show this behaviour is different everyday, also the number of panels is different. Today 6 out of 9 have a problem. Yesterday they were all correct.

Any idea if this can be fixed?

Wrong:
![image](https://user-images.githubusercontent.com/114749726/197508761-64f3bb46-5224-469b-aeb2-0c34bc32d9d1.png)

Correct:
![image](https://user-images.githubusercontent.com/114749726/197508830-86b336c0-8169-4ab7-a4c4-2246efa30fa3.png)

**Comment by ProudElm** [comment]
This is weird. I just checked my sensor and it has the same drop-off.. Not sure what could be causing this yet. I will take a look.

**Comment by B1rdEater** [comment]
Thanks for investigating!

**Comment by B1rdEater** [comment]
Today:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Henri/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Henri/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Panel/Date | 25-10-2022
-- | --
1.0.1 | X
1.0.2 | X
1.0.3 | X
1.0.4 | X
1.0.5 | X
1.0.6 | X
1.0.7 | X
1.0.8 | V
1.0.9 | V



</body>

</html>

**Comment by B1rdEater** [comment]
Today's score. I will keep track; see if there is a clue.

![image](https://user-images.githubusercontent.com/114749726/197748605-0e92ef06-25a2-44c5-842d-fa0222e5a448.png)

**Comment by B1rdEater** [comment]
Yeah, there is a really high chance that the problem is at SolarEdge its side. If so, can we submit a bug there?
Would be great if somehow you would be able to build a logic that prevents this drop with faulty data

**Comment by ProudElm** [comment]
Uhm wel.. i kind of 'hacked' the data from the portal site. So if a bug report is a good idea..? :)
Kind of looks like a recalculation off the value of the optimizers when a new day happens.. It alway just a few wh..

I'm looking into if a round the value if this issue can be solved.

**Comment by B1rdEater** [comment]
Whaha; well, than our best option won't be to tell SE about your intrusion. And indeed, it it just a few wh, but it messes up the utility meters big time, they will not start at 0.

![image](https://user-images.githubusercontent.com/114749726/197757872-8e32f85b-2afe-431d-bea3-d5e65f542881.png)

**Comment by B1rdEater** [comment]
Small update (was away for a few days). Affected panels seem to very A lot..

![image](https://user-images.githubusercontent.com/114749726/198977241-e56f64cb-bd16-4c31-a603-a36936b23879.png)

**Comment by ProudElm** [comment]
Yes, i cant find a reason why.

I can solve it by checking the new value against the current one (i think) and only allow a new value if greater then the old value.
I hoped not to intervene to much in de data received, but it seems there is no other option. 

I will try to release a fix for it this week.

**Comment by B1rdEater** [comment]
Sounds like a plan. Thanks for this fix; I will test it when you release the update

**Comment by ProudElm** [comment]
With the latest release (v1.1.2) this wont happen again.

**Comment by B1rdEater** [comment]
Seems to fail :(

![image](https://user-images.githubusercontent.com/114749726/200779322-c73470bd-be70-427e-a2e9-5757a39a376f.png)

![image](https://user-images.githubusercontent.com/114749726/200779396-873b7f05-6eda-4a08-bb35-0a6515322fd8.png)

**Comment by ProudElm** [comment]
ai, that's weird... it should not update the sensor when the value is lower then its previous state.

Let me know if it happens again tomorrow, in the mean time, i will debug some more.

**Comment by B1rdEater** [comment]
Yeah, its strange. I will check again tomorrow!

**Comment by B1rdEater** [comment]
So far so good! How strange it didn't work yesterday. I will keep checking for a few days :)

**Comment by ProudElm** [comment]
I found the problem... It was a stupid.. Next release it will be fixed (again)

**Comment by B1rdEater** [comment]
It happens :). Thanks!

**Comment by B1rdEater** [comment]
I am afraid that update somehow broke some other sensors, no new update for te last 2 hours:

![image](https://user-images.githubusercontent.com/114749726/201124441-967e450a-01f4-41e1-abfa-8a710d155229.png)

![image](https://user-images.githubusercontent.com/114749726/201124569-9df596c9-2fb4-4772-b2f6-d07a63ce6004.png)

![image](https://user-images.githubusercontent.com/114749726/201124641-3073923a-28b6-424c-93f4-deb3cffaecdf.png)

![image](https://user-images.githubusercontent.com/114749726/201124754-e743eb65-2cb8-4d36-97eb-6d790abc02a3.png)

Only lifetime-sensor keeps sending updates:

![image](https://user-images.githubusercontent.com/114749726/201124936-33adf0b5-802a-4b52-9947-17c05a8b6198.png)

**Comment by B1rdEater** [comment]
Seems alright now; all sensors and no dip in lifetime :D

**Comment by ProudElm** [comment]
Nice! I will keep this issue open for a few more day's, just to be sure its really fixed ;-)

**Comment by B1rdEater** [comment]
Smart move. Lets hope I get some more sun.. because its grey as hell at the moment here xD

**Comment by B1rdEater** [comment]
Looking good! (inside blue square= SolarEdge; other = Enphase).

![image](https://user-images.githubusercontent.com/114749726/201515888-93ae03f6-10e1-45fc-8dbf-71717c2c8f9f.png)

**Comment by ProudElm** [comment]
@B1rdEater How is the data performing? Is it still stable?

**Comment by B1rdEater** [comment]
Daily lifetime is functioning as expected and stable.

Not sure what happened yesterday with other sensors; but they were offline for some time. At the moment they are working as they should. See history. Red: power outages. Blue: can't explain why data was not available.

![image](https://user-images.githubusercontent.com/114749726/203993751-aecff8d3-6f8a-491e-99f3-a4424bd4bbcc.png)

**Comment by ProudElm** [comment]
nice to hear.

It's just a bit tricky some times. I want to refactor the way the data is retrieved, but i need to find out how ;-)

**Comment by B1rdEater** [comment]
I understand! I think this issue can be marked as solved now :)

**Comment by B1rdEater** [comment]
Mm, now I look at it again my sensors have been frozen for the past 3 hours (except lifetime).

The response was: {"194373381":{"energy":291.07,"moduleEnergy":291.07,"unscaledEnergy":291066.75,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373380":{"energy":280.95,"moduleEnergy":280.95,"unscaledEnergy":280954.0,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373383":{"energy":291.55,"moduleEnergy":291.55,"unscaledEnergy":291546.75,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373382":{"energy":276.41,"moduleEnergy":276.41,"unscaledEnergy":276412.5,"units":"kWh","color":"#2D89E5","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"196662828":{"energy":2.52,"moduleEnergy":0.28,"unscaledEnergy":2517418.0,"units":"MWh","color":"#30F291","groupColor":"#3091F2","relayState":null,"cellularConnectionProperties":{"connectionType":"STANDARD","connectionFailure":null,"connectable":true}},"194373379":{"energy":2.52,"moduleEnergy":0.28,"unscaledEnergy":2523602.0,"units":"MWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":{"connectionType":"STANDARD","connectionFailure":null,"connectable":true}},"194373388":{"energy":280.11,"moduleEnergy":280.11,"unscaledEnergy":280106.0,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373385":{"energy":281.27,"moduleEnergy":281.27,"unscaledEnergy":281272.5,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373384":{"energy":286.23,"moduleEnergy":286.23,"unscaledEnergy":286229.75,"units":"kWh","color":"#3091F2","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373387":{"energy":270.88,"moduleEnergy":270.88,"unscaledEnergy":270877.75,"units":"kWh","color":"#2D89E5","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null},"194373386":{"energy":265.14,"moduleEnergy":265.14,"unscaledEnergy":265136.0,"units":"kWh","color":"#2D89E5","groupColor":"#000000","relayState":null,"cellularConnectionProperties":null}}

**Comment by B1rdEater** [comment]
Also, this freezing creates the same old problem. Sorry, I was to quick :(

![image](https://user-images.githubusercontent.com/114749726/204003609-8c66b100-88ae-4c59-8795-8e4b760b30f0.png)

**Comment by B1rdEater** [comment]
Logger: custom_components.solaredgeoptimizers.sensor
Source: custom_components/solaredgeoptimizers/sensor.py:201
Integration: SolarEdge Optimizers Data ([documentation](https://github.com/ProudElm/solaredgeoptimizers), [issues](https://github.com/ProudElm/solaredgeoptimizers/issues))
First occurred: 24 november 2022 om 02:47:17 (15 occurrences)
Last logged: 13:49:42

'<=' not supported between instances of 'str' and 'float'
'<=' not supported between instances of 'float' and 'str'
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by B1rdEater** [comment]
As expected; just started today.... have a look at all daily yield graphs from the past 3 days. Today.. is kind of broken

![image](https://user-images.githubusercontent.com/114749726/204004495-ac79904a-3655-4c04-ab8c-0c5c32202f0f.png)

**Comment by ProudElm** [comment]
mmm... strange... does your system restart at 0.00? Causing those sharp declines perhaps?

Back to the drawing board i gues it is..

**Comment by B1rdEater** [comment]
There is a lot of errors going on, that I haven't seen before. Is the code maybe broken somehow?

![image](https://user-images.githubusercontent.com/114749726/204084988-e5decb7b-d585-4e13-bcc2-4d12832b8621.png)

**Comment by ProudElm** [comment]
not sure.. i'm seeing a lot of errors too.. I will try to make time this week to look into it!

**Comment by B1rdEater** [comment]
Hopefully it is not too serious :(

**Comment by B1rdEater** [comment]
It seems its officially dead now :(

![image](https://user-images.githubusercontent.com/114749726/208237997-45a2836c-091f-43fb-89e5-cedb6689a816.png)

**Comment by ProudElm** [comment]
even after a reboot? I found one bug (not fixed) that is causing it to stop sometimes.. but a reboot solves this (temporally).

**Comment by B1rdEater** [comment]
Yes that works!

**Comment by ProudElm** [comment]
With the latest release it should me way more stable now, Can you let met know if it is indeed a lot better now?

**Comment by B1rdEater** [comment]
Sure! Waiting for HACS to pick-up the latest release first :)

**Comment by B1rdEater** [comment]
Updated last week and haven't spotted any error in the logging since. Looking good mate :)

**Comment by B1rdEater** [comment]
![image](https://user-images.githubusercontent.com/114749726/216812775-65057cf0-17ea-42b0-aa08-d864b80050a2.png)

Shit :(

**Comment by ProudElm** [comment]
uhm. please help me, what's wrong? I think way more then your expecting? What sensor are you displaying there?

**Comment by B1rdEater** [comment]
Its the lifetime sensor of some panels that is again dipping (issue we had before, see image below).

![image](https://user-images.githubusercontent.com/114749726/216828591-bd6c33a8-c3b6-4da3-939e-f98dd1f15cd7.png)

**Comment by ProudElm** [comment]
ai.. i will check.. I hope its an easy fix..

**Comment by B1rdEater** [comment]
@ProudElm : problem still exists, did you manage to have a look a this?

![image](https://github.com/ProudElm/solaredgeoptimizers/assets/114749726/247d2ebf-ff74-4e32-a991-42663dddcfc0)

**Comment by ProudElm** [comment]
no not yet. i've started working again on this integration a few days ago, but i hate my dev-env. It is not stable to get it working. i will keep trying

**Comment by B1rdEater** [comment]
Good to hear you picked up on the work here :). Hope you succeed in fixing this!

**Comment by B1rdEater** [comment]
Any updates yet? This issue is closed; but the problem still exists :(

**Comment by B1rdEater** [comment]
HI ProudElm! Has been a few months; did you manage to have a look at this issue?
