### ISSUE TITLE
Total energy for panel

### ISSUE THREAD

**Issue by stepsolar** [ProudElm/solaredgeoptimizers#14]
Would it be possible to enter the total amount of energy produced on each individual panel?  Thank's for your job

**Comment by ProudElm** [comment]
Cant you handle this not better via a template sensor? At least, if i understand you correctly? You want to enter the total amount of energy (kWh) produced per panel? Not the lifetime energy already provided but a custom number?

**Comment by ProudElm** [comment]
You should have also a life time energy sensor. This is the total energy produced by the panel. 
![image](https://user-images.githubusercontent.com/15194287/206723256-3ebd5389-6ad0-4260-8ea5-d0e21628d8dc.png)
This sensor should not reset per day but just keep on growing..

**Comment by stepsolar** [comment]
Lifetime energy sensor is fine. But if it would be possible to insert an energy sensor of the day

**Comment by ProudElm** [comment]
You can better use a utility meter from HA self. Use the life time sensor ass input and set the reset time to daily. Then you have a daily sensor. While your at it, use month/year too ;-)

**Comment by stepsolar** [comment]
and what i am trying to do. Anyway thanks

**Comment by stepsolar** [comment]
I can't get the same result shown in thesolardge app, could you help me thanks

**Comment by stepsolar** [comment]
Greetings,
i almost managed to create the sensors but i wonder why in your project you didn't put the fetch of this data from the link "https://monitoring.solaredge.com/solaredge-apigw/api/sites/xxxxxx/layout/logical"
the color of the panel is also reported. You could create a card that changes color as shown in the Solardge screen

![image](https://user-images.githubusercontent.com/84263865/206897867-6fc5b389-3ad0-41c2-9620-b727c2bb6e6d.png)


Thank you

**Comment by ProudElm** [comment]
uhm never thought of it nor did i think i would use it..  There are still some issues with the code i need to sort out but dont have the time for.. those are my priority for now.

**Comment by ProudElm** [comment]
Is this issue still valid or can i close it?

**Comment by stepsolar** [comment]
.
