### ISSUE TITLE
Not all panels found

### ISSUE THREAD

**Issue by freijn** [ProudElm/solaredgeoptimizers#18]
Many thanks for your work !  Really happy with it but....

The number panels found is stuck at 19 where I have 22.
Its running for 3 days now.

Any clue / hint?

THanks in advance.

     Frank

**Comment by ProudElm** [comment]
What version is installed? It looks to default to version 1.1.3 while 1.1.4 is the most recent one?

**Comment by spady7** [comment]
Hi, I' ve same issue. loaded 23 panels, but i've 28.
Installed v. 1.1.3 (compared to v. 1.1.4 there is not differences)
Any idea?

**Comment by freijn** [comment]
After a few days, finnally all mu 22 panels are discovered. I Will see if i
can find anything in the logfiles.
Perhaps a small note in the install guide might be helpfull.

Op di 20 dec. 2022 12:28 schreef spady7 ***@***.***>:

**Comment by ProudElm** [comment]
mm...strange that after a time it does work.. dit you reboot perhaps?

@spady7 What could help is rebooting but if you can, could you send me the json response from:
https://monitoring.solaredge.com/solaredge-apigw/api/sites/<<YOUR_SITE_ID>>/layout/logical (change the part with your site_id).

You can email it to me. Than i can debug the response and check if there are some issues that could be causing not adding all the panels.

**Comment by freijn** [comment]
Not reboot, but reload, after the update and yaml change. But the first 4
appeared a few min after implementatie. Then nothing and then after a few
days all have been found. I am remote but Will search the logfile for
details.

Op di 20 dec. 2022 12:51 schreef ProudElm ***@***.***>:

**Comment by spady7** [comment]
> mm...strange that after a time it does work.. dit you reboot perhaps?
> 
> @spady7 What could help is rebooting but if you can, could you send me the json response from: https://monitoring.solaredge.com/solaredge-apigw/api/sites/<<YOUR_SITE_ID>>/layout/logical (change the part with your site_id).
> 
> You can email it to me. Than i can debug the response and check if there are some issues that could be causing not adding all the panels.

@ProudElm now seams to be ok. It takes around 30 min to get all data panels e panels too. Now seams to be ok.

**Comment by freijn** [comment]
> You can email it to me. Than i can debug the response and check if there are some issues that could be causing not adding all the panels.

Can you let me know how I can find your email address? pls

**Comment by ProudElm** [comment]
You can mail me at proudelm@yahoo.com

**Comment by ProudElm** [comment]
@freijn Is this issue still active? If not, i will close it!

**Comment by freijn** [comment]
After some days it did find all my panels.  You can close this issue.
Many thanks for your patience.

**Comment by ProudElm** [comment]
Good to read! Your welcome!
