### ISSUE TITLE
Error fetching SolarEdgeOptimizer data: 'AEST'

### ISSUE THREAD

**Issue by genesispc** [ProudElm/solaredgeoptimizers#23]
I am getting this error after updating to version 1.2.0. Version 1.1.4 works fine.

This error originated from a custom integration.

Logger: custom_components.solaredgeoptimizers.sensor
Source: helpers/update_coordinator.py:215
Integration: SolarEdge Optimizers Data (documentation, issues)
First occurred: 9:04:29 AM (1 occurrences)
Last logged: 9:04:29 AM

Error fetching SolarEdgeOptimizer data: 'AEST'

**Comment by ProudElm** [comment]
Yep, i know the problem. There's an issue with timezones..

Im working on the issue. See:
https://github.com/ProudElm/packaging_solaredgeoptimizers/issues/1

**Comment by genesispc** [comment]
Thanks for the update. Version 1.2.1 works a treat.
Now to try and implement that dashboard that you had detailed in on of the 'issues' :-)

**Comment by ProudElm** [comment]
Thank you, good to hear! Good
