### ISSUE TITLE
"Invalid authentication"

### ISSUE THREAD

**Issue by johnconn73** [ProudElm/solaredgeoptimizers#3]
Hmm.  I get "invalid authentication" when I try to add the credentials into the integration flow. I know the credentials are correct.

Will this work with a regular Genesis HD inverter or does it need the Energy Hub version, or the Genesis Enhancement Pack (which adds panel level monitoring)?  I don't have the enhancement pack and am just on a standard Genesis inverter (SE8250H).

**Comment by ProudElm** [comment]
hi, i think it should work. But this code gathers information from the SolarEdge-web portal. Do you have acces to this site? Where you can see the information from the individual optimizers?

**Comment by johnconn73** [comment]
I have access to the solaredge-web portal, but it doesn't expose the optimiser/panel data.  In Australia at least, to get access to that you need either the Energy Hub inverter or pay separately for the Genesis Enhancement Pack. Neither of which I have https://www.solaredge.com/aus/genesis-enhancement

**Comment by ProudElm** [comment]
ai damm.. That's not nice.. Then this method cant work for you 👎 I'm sorry.

**Comment by timovd** [comment]
Inverter: 1phase SE2200 with screen
It doesn't work with my "consumer" login, but it works with my self-installer login.

**Comment by ProudElm** [comment]
This is then related to the portal and acces it self i gues? Nothing i can dot here i think.
