### ISSUE TITLE
Second system

### ISSUE THREAD

**Issue by scannie67** [ProudElm/solaredgeoptimizers#32]
I have two SolarEdge inverters. 
Site-id is not the same. 
Is it possible to add a second system?
I want to see the optimizer information from both systems.

**Comment by ProudElm** [comment]
Im not sure what happens. I think it will work, but i did not prepared the naming of the sensors for this case. I will try to test it.. ;-)

**Comment by ProudElm** [comment]
It should work, the sensors are getting a unique_id based on the serial number. 

Let me know if it worked!

**Comment by scannie67** [comment]
Every inverter has it own api and site-id. 
Also the password is not the same. 
But I can only fill in one. 
There is no option for the second one.

**Comment by ProudElm** [comment]
You can just add an other instance of the same integration. Just add it again in HA en fill in the other side-id. This should work i think. The main problem could be the sensor names, but as far as unique-id's, that is using the serial number of the panel, so it should be unique even when using 2 systems.

**Comment by ProudElm** [comment]
@scannie67 Did it work?

**Comment by scannie67** [comment]
I donn’t know. The SolarEdge inverter is defective at this moment. After repair I try again. Op 5 mrt. 2023 om 20:10 heeft ProudElm ***@***.***> het volgende geschreven:﻿
@scannie67 Did it work?

**Comment by ProudElm** [comment]
Ai, i'm sorry to hear that. Good luck with the repairs.
