### ISSUE TITLE
i can install the integration without issue but does not create any entities or devices

### ISSUE THREAD

**Issue by Menz01** [ProudElm/solaredgeoptimizers#35]
Hello,
    i have no issue installing the integration. it accepts my username and password and site id but after that it does not show me anything. if i look at it there are no devices and no entities

**Comment by ProudElm** [comment]
Are there any errors in de logging in HA?

**Comment by Menz01** [comment]
> Are there any errors in de logging in HA?
> 
> Sometimes it can take a while, there are issues with performance on the SolarEdge portal side

not seeing anything in the logs but i'll admin i am not sure i am looking correctly. How much "time" should i wait? it's been over 48 hours now since i installed it

**Comment by ProudElm** [comment]
oh, that's to long.. 

Perhaps remove the integration and try again? And check the home assistant logs for any errors or issues. Any error should be logged there.

**Comment by Menz01** [comment]
I have removed the integration and re-added it a few times. never an error on the main screen but nothing shows after its added. i even put in my username wrong just to make sure an error would show and it did for that. not seeing anything in the logs. Perhaps i am not looking in the correct spot? can you detail how to get to the logs i should be seeing so i can see if i am doing it right?

**Comment by ProudElm** [comment]
The HA logs are located @ settings ->System -> Logs.
If the integration has any errors, those should be available there.

**Comment by Menz01** [comment]
so i opened two browser windows... one to the logs are you outlined and the other to the integrations page. i then uninstalled your integration and then re-installed it and there were zero entries in the logs. nothing at all changed from the last entry in the log before i started. i even refreshed and did not see any entries related to your integration.

**Comment by ProudElm** [comment]
With install you mean in HA self, thus entering the site-id etc?

Can you if you want please send me the JSON result of the following request? So i could debug it here?
https://monitoring.solaredge.com/solaredge-apigw/api/sites/<SITE_ID>/layout/logical

Thanx!

**Comment by Menz01** [comment]
yes... i go to setting then devices and services, click the add
integration, search for your integration and add it. when it asks i put in
the site id, username and password and click ok and the integration adds
but nothing is there.

how do i get the JSON you are asking for? i go to that link and all i get
is a black page with all sorts of code on it

**Comment by Menz01** [comment]
i think i figured it out

**Comment by Menz01** [comment]
> With install you mean in HA self, thus entering the site-id etc?
> 
> Can you if you want please send me the JSON result of the following request? So i could debug it here? https://monitoring.solaredge.com/solaredge-apigw/api/sites/<SITE_ID>/layout/logical
> 
> Thanx!
[logical.zip](https://github.com/ProudElm/solaredgeoptimizers/files/10864383/logical.zip)

**Comment by ProudElm** [comment]
Thank you!

I see you have some thing like a production meter? I did not know this was even possible. 
I now know the problem, i need to rework some code to make sure this wont be an issue any more.

**Comment by ubarni** [comment]
Looks i am having the same issue (no entities created) and added my logical json and a screenshot.

<img width="932" alt="Bildschirm­foto 2023-03-03 um 04 14 35" src="https://user-images.githubusercontent.com/5228490/222622417-2174502c-5b72-4cc1-8e98-b1778edcf9da.png">

[logical_2686247.zip](https://github.com/ProudElm/solaredgeoptimizers/files/10877851/logical_2686247.zip)

**Comment by ProudElm** [comment]
Thank you. I

**Comment by ProudElm** [comment]
I seem to have solved it. I will test some more and try to publish the fix tomorrow.

it seems my original test case (me myself and i) was not valid enough for all the different possibilities out there ;-) Hopefully most cases are now solved

**Comment by ubarni** [comment]
Congratulations. Now my Optimizers were found 🥰 Thank You... 
<img width="568" alt="Bildschirm­foto 2023-03-05 um 14 32 14" src="https://user-images.githubusercontent.com/5228490/222963653-03e411c0-06b9-418a-b227-0b5716a3c39a.png">

**Comment by ProudElm** [comment]
Nice! Your welcome!

**Comment by Menz01** [comment]
mine are now being found too... wow so many of them!!! thanks

**Comment by Menz01** [comment]
![image](https://user-images.githubusercontent.com/31291495/222985781-374efe1d-764b-4058-9336-881f0e2f6e47.png)
