### ISSUE TITLE
Integration only finds 16 of 28 optimizers

### ISSUE THREAD

**Issue by 2xdehelft** [ProudElm/solaredgeoptimizers#36]
Hi,

Great integration! Nice to have the solaredge optimizer data in Homeassistant. Strange thing is it only detects the first 16 optimizers of 28 in total.

Any idea why? Please let me know if I can help in any way.

**Comment by ProudElm** [comment]
All the optimizers are on 1 inverter? 
No errors or warnings in the HA log?

**Comment by 2xdehelft** [comment]
Only this in logging : Setup of sensor platform solaredgeoptimizers is taking over 10 seconds.

They are all on one inverter and one string, but different types of optimizers and panels (but they are compatible)

**Comment by 2xdehelft** [comment]
Nevermind.. did an extra reboot of HASS, now all 28 are visible...

Thanks for the support!

**Comment by ProudElm** [comment]
Oh nice!

I'll need to add this to the read-me.. It can take some time or a restart sometimes.. :-(
