### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by shrike8t** [ProudElm/solaredgeoptimizers#41]
Hi,

I was wondering can this be merged or used in combination with the solaredge integration?

Regards,

Bart Janssens

**Comment by ProudElm** [comment]
I think it's better let separate. For me at least, i don't use the solaredge integration but the modbus version. That last one is real time and way better then any cloud based version. My wish is that one day we can also get the optimizes information from the modbus. Then my integration is no longer needed :)
