### ISSUE TITLE
Latest update from HA crashed addon 

### ISSUE THREAD

**Issue by Dutchy-79** [ProudElm/solaredgeoptimizers#52]
Hi,

Just noticed that since I installed the new HA version of June this addon is no longer working.

**Comment by ProudElm** [comment]
i will take a look. i did not have any time and my dev env is broken.

**Comment by ProudElm** [comment]
Is this still the case? I just installed it in my dev env with HA version:
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

And for now, it seems to just work..

**Comment by Dutchy-79** [comment]
Works now for me, forgot to tell you.

**Comment by ProudElm** [comment]
no problem. Glad it works!
