### ISSUE TITLE
solaredgeoptimizers.py missing

### ISSUE THREAD

**Issue by RichieB2B** [ProudElm/solaredgeoptimizers#55]
On January 10th, 2023 in commit 7ea6b24ae578845b9fe8af4e717fa79bca7d2139 of v1.1.9 you removed `custom_components/solaredgeoptimizers/solaredgeoptimizers.py`

How this module can work without it puzzels me as it is now at v1.2.4 and `solaredgeoptimizers.py` is still imported in various places.

**Comment by ProudElm** [comment]
It has been added to PyPi and this installed via pip install when installing the add-on.

**Comment by RichieB2B** [comment]
The [version on PyPi ](https://pypi.org/project/solaredgeoptimizers/) is using another repo https://github.com/ProudElm/packaging_solaredgeoptimizers which still has `solaredgeoptimizers.py` but none of the improvements from this repo. How are these two repos related?

**Comment by ProudElm** [comment]
This repo is the integration for in HA.
The orther repo (packaging_solaredgeoptimizers) is the python file for communication between the integration and the solaredge web portal. 

When i have a little more time, all improvements are added to either this repo or the other one. Depending on where the changes belong.
