### ISSUE TITLE
Sensor names

### ISSUE THREAD

**Issue by Giel538** [ProudElm/solaredgeoptimizers#6]
Hi,

Is is possible that all sensor names are a bit more specific. 

For example: sensor.current, sensor.current_2, etc.

Is it possible to get something like this: sensor.optimizer1_1_1_current, sensor.optimizer1_1_2_current, etc.

If i have for example allready a sensor.current and i load this plugin i got for my first panel sensor.voltage, sensor.power and for current: sensor.current_1

**Comment by ProudElm** [comment]
In the next version this should be fixed. But i will check to make sure.

**Comment by Giel538** [comment]
I see version first in HA but i cannot update. Nothing happands after pressing update button

**Comment by ProudElm** [comment]
I know, i messed something up with this tag/release.. 👎

**Comment by ProudElm** [comment]
Laters release works again in HACS and uses the now better naming.

**Comment by Giel538** [comment]
still not been able to update.

**Comment by Giel538** [comment]
after some deleting and re-adding i am been able to update from 1.03 to 1.04

sensor names did not change or do i need to re-add the integration? or wait longer ?

**Comment by ProudElm** [comment]
Ok thanx! i was not sure if the names would auto-update. But i guess they don't.  Now we know for sure. Thank you!

Good point, i will look into that ;-) Thanx!
