### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by Vaszago** [ProudElm/solaredgeoptimizers#65]
When starting the abb I get the following error "The configuration flow could not be loaded: 500 Internal Server Error Server got itself in trouble". Has been since the update 2024.2.2. Even a reinstallation didn't fix the error.

**Comment by jhuang0** [comment]
Mine is unable to connect as well.

**Comment by Vaszago** [comment]
Has been working again for a few days.

**Comment by jhuang0** [comment]
Yeah... it only went out for that brief period of time. Everything's looking good now. Thanks!

**Comment by ProudElm** [comment]
Nice! Good luck
